// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcrkfhttudvjkqchyceh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjcmtmaHR0dWR2amtxY2h5Y2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDgyNzIsImV4cCI6MjA2MDk4NDI3Mn0.y2nv1gQlwrlI0X03FdXCGs9fh2QK-v7DEi7QaIWaoWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);